# Generated by Django 3.0.5 on 2020-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='id',
            field=models.AutoField(auto_created=True,  serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
